### PR TITLE
CCS 163279: Added VPC parameters and lansa version

### PR DESCRIPTION
**Pull request by SakshamAccolite**
Added VPC parameters and lansa version

### CODE REVIEW

**Comment by robe070** [comment]
Your base seems to be way behind lansa/aws-template support/scalable. Please rebase onto this and re-commit.

**Comment by SakshamAccolite** [comment]
Hi @robe070 , Kindly review. Also I have added the parameter "TemplateS3Namespace". Kindly let me know if needs to be hidden.

**Comment by robe070** [comment]
TemplateS3Namespace is not required. Customer's don't need it and the template pipeline doesn't/won't use it.
Image pipeline doesn't use Shoe Sizes because it tests custom images.

**Comment by SakshamAccolite** [comment]
I've removed "TemplateS3Namespace" @robe070 . Kindly review.

**Comment by robe070** [comment]
Looks correct. Haven't created stacks. Must get back to looking at why pipelines are failing to create stacks

**Pull request merged**
