### PR TITLE
Feature/103

### PR DESCRIPTION
**Pull request by sharirpcs**

### CODE REVIEW

**Comment by robe070** [comment]
Why are these old commits in the PR?
Why have you pushed commits when you haven't tested them locally first?

**Comment by robe070** [comment]
Rebase on support/scalable and then squash all the commits.

**Comment by robe070** [comment]
Changes look good.
Now you need to squash the commits

**Comment by sharirpcs** [comment]
The Parameter combinations I have used is AllocatedStorage = 10000 and DBIOPRatio = 30.It throws the below error

> Invalid iops value for engine name sqlserver-web and storage type io1: 64000 (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: a6da9c9d-8cd1-465a-b325-b4f91e1e2cfc; Proxy: null)


Please refer to this URL for the issue https://ap-southeast-2.console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stacks/parameters?filteringStatus=active&filteringText=&viewNested=true&hideStacks=false&stackId=arn%3Aaws%3Acloudformation%3Aap-southeast-2%3A775488040364%3Astack%2FTestmastercfn18%2F2687ca20-f426-11eb-8cc6-06533efcbfa4

**Comment by robe070** [comment]
For the purposes of the error, in AWS terms, I think that translates into 
Engine = sqlserver-web
iops = 64000
Storage type= io1
Allocated Storage = 10000

Have you tried iops = 63999 and iops =  32000? I did ask you to try various combinations to see what works and what does not. It might be easier to use the portal to create a DB Instance and play with the values there.

**Comment by sharirpcs** [comment]
I have tried with the below combination:

Engine=sqlserver-web
Allocated storage =10000
DBIOPSRatio=30
Databaseconfiguration=db.m5.4xlarge

The above combination got successfully created the stack.Here is the stack URL

 https://ap-southeast-2.console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stacks/parameters?filteringStatus=active&filteringText=&viewNested=true&hideStacks=false&stackId=arn%3Aaws%3Acloudformation%3Aap-southeast-2%3A775488040364%3Astack%2FTestmastercfn19%2Fff4894f0-f5b3-11eb-8c14-0aaf2d46a68a

**Comment by sharirpcs** [comment]
IOPS 32000 with the below combinations is getting created

Engine=sqlserver-ex
Allocated storage =1000
DBIOPSRatio=32
Databaseconfiguration=db.t3.small

Here is the stack URL https://ap-southeast-2.console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stacks/events?stackId=arn%3Aaws%3Acloudformation%3Aap-southeast-2%3A775488040364%3Astack%2FTestmastercfn20%2F418420c0-f5c6-11eb-8a74-0253c0cbd21e&filteringStatus=active&filteringText=&viewNested=true&hideStacks=false

**Comment by sharirpcs** [comment]
Screenshot 2021-08-05 at 1 58 32 PM
As per AWS document IOPS=64000 is supported on the m5, m5d, r5, r5b, r5d, and z1d instance types.And other instance types will support IOPS=32000

**Comment by sharirpcs** [comment]
IOPS 63999 with below combinations

Engine=sqlserver-web
Allocated storage =4923
DBIOPSRatio=13
Databaseconfiguration=db.m5.4xlarge

Here is the stack URL https://ap-southeast-2.console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stacks/parameters?stackId=arn%3Aaws%3Acloudformation%3Aap-southeast-2%3A775488040364%3Astack%2FTestmastercfn21%2F50134850-f611-11eb-80ac-0246f7a6da62&filteringStatus=active&filteringText=&viewNested=true&hideStacks=false

**Comment by robe070** [comment]
Thats very clear. Thank you for the references. The Note about IOPS of 64000 is clearly not just about a guarantee,  its actually enforced.

So, a rule and an assertion is required to apply this Note.

And, you can submit another commit, there is no need to keep squashing. There were just too many related or extraneous commits previously. Submitting a new commit now helps me to focus on what you have changed.

**Comment by robe070** [comment]
I think there is some value in checking for 64000, given its the value used in the lambda function when the result is greater than 64000. Test using "db.m5" as one of the test values. If that matches db.m5.2xlarge then also use the same logic for the other rules that were documented as matching db.m5.*, etc.

And another change is required to inform the user of the 32000 limit. We'll have to leave that to updating the description. Replace the parameters with the following:
```
    "19DBAllocatedStorage": {
      "Default": "100",
      "Description": "The maximum size of the database. Must be between 20 and 16384 GB. Minimum 20 for 'sqlserver-ex'. For other database engines the minimum is 100",
      "Type": "Number",
      "MinValue": "20",
      "MaxValue": "16384"
    },
    "DBIOPSRatio": {
      "Default": "10",
      "Description": "If IOPS Ratio > 1 then StorageType = io1 and IOPS will be set to Allocated Storage x IOPS Ratio, otherwise StorageType = gp2 and IOPS will be set to NULL. IOPS must be less than or equal to 32,000, unless using Nitro-based instances that are on the m5, m5d, r5, r5b, r5d, and z1d instance types",
      "Type": "Number",
      "MinValue": "0",
      "MaxValue": "50"
    },
```

**Comment by sharirpcs** [comment]
Here is the stack  test URL  for "db.m5.xlarge" instance type
https://ap-southeast-2.console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stacks/resources?stackId=arn%3Aaws%3Acloudformation%3Aap-southeast-2%3A775488040364%3Astack%2FTestmastercfn22%2F18a5c620-f686-11eb-bb96-0a6e1e179d0a&filteringStatus=active&filteringText=&viewNested=true&hideStacks=false

**Comment by sharirpcs** [comment]
Here is the stack test URL for "db.m5.2xlarge" instance type.
https://ap-southeast-2.console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stacks/resources?stackId=arn%3Aaws%3Acloudformation%3Aap-southeast-2%3A775488040364%3Astack%2FTestmastercfn23%2F7ff83450-f688-11eb-9b94-028a54ef857c&filteringStatus=active&filteringText=&viewNested=true&hideStacks=false

**Comment by sharirpcs** [comment]
Here is the stack test URL for "db.m5.8xlarge" instance type and DBEngine =sqlserver-se.
https://ap-southeast-2.console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stacks/events?stackId=arn%3Aaws%3Acloudformation%3Aap-southeast-2%3A775488040364%3Astack%2Ftestmastercfn24%2F55a36230-f68b-11eb-913b-0275e2ecfe7c&filteringStatus=active&filteringText=&viewNested=true&hideStacks=false

**Comment by sharirpcs** [comment]
Here is the stack test URL for "db.m5.large" instance type.
https://ap-southeast-2.console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stacks/events?stackId=arn%3Aaws%3Acloudformation%3Aap-southeast-2%3A775488040364%3Astack%2FTestmastercfn25%2F4424aa40-f68c-11eb-bca7-02bc295cfb64&filteringStatus=active&filteringText=&viewNested=true&hideStacks=false

**Comment by sharirpcs** [comment]
Here is the stack test URL for "db.m5.12xlarge" instance type and DBEngine =sqlserver-se.
https://ap-southeast-2.console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stacks/events?filteringStatus=active&filteringText=&viewNested=true&hideStacks=false&stackId=arn%3Aaws%3Acloudformation%3Aap-southeast-2%3A775488040364%3Astack%2FTestmastercfn26%2F6fd788f0-f68d-11eb-935d-02ee5c9748d8

**Comment by robe070** [comment]
So you are testing that you can successfully deploy with IOPS of 64000 with various combinations of instance type?

**Comment by sharirpcs** [comment]
Here is the stack test URL for "db.m5.16xlarge" instance type and DBEngine= sqlserver-se.
https://ap-southeast-2.console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stacks/events?stackId=arn%3Aaws%3Acloudformation%3Aap-southeast-2%3A775488040364%3Astack%2FTestmastercfn27%2F19b6ee60-f68e-11eb-9ab8-02fd8d8ea4a6&filteringStatus=active&filteringText=&viewNested=true&hideStacks=false

**Comment by sharirpcs** [comment]
Here is the stack test URL for "db.m5.24xlarge" instance type and DBEngine= sqlserver-ee.
https://ap-southeast-2.console.aws.amazon.com/cloudformation/home?region=ap-southeast-2#/stacks/events?filteringStatus=active&filteringText=&viewNested=true&hideStacks=false&stackId=arn%3Aaws%3Acloudformation%3Aap-southeast-2%3A775488040364%3Astack%2FTestmastercfn30%2Fedf959f0-f68f-11eb-a97e-0aa93ce2a038

**Comment by sharirpcs** [comment]
I have tested with the various combinations of the instance types and got successfully deploying the IOPS of 64000.Please review the Test stack URLs

**Comment by robe070** [comment]
Looks good. Please delete all the stacks you have created

**Comment by sharirpcs** [comment]
Yeah sure.I will do it now

**Comment by sharirpcs** [comment]
I have deleted all the stacks.If everything looks good then please merge this PR and close this ticket

**Comment by robe070** [comment]
This PR will not be merged until the JPN images have been published.

**Comment by robe070** [comment]
This is incorrect
```
        "DBIOPSRatio": {
          "default": "10"  
        },
```
should be this
```
        "DBIOPSRatio": {
          "default": "Database IOPS Ratio"  
        },
```
This is not used. Remove it.
```
      "DatabaseStorageType": {
        "Value": ""
      }
```

**Comment by sharirpcs** [comment]
I have made the changes and tested it again.The Parameter label is displaying as "Database IOPS Ratio".Please refer the attached screenshot
Screenshot 2021-08-07 at 12 05 59 PM

**Comment by lansaeval57** [comment]
Actually posted by @robe070.

That looks correct now.

Please squash all the commits into 1 commit.

**Comment by sharirpcs** [comment]
Squashed all the commits into one commit

**Comment by sharirpcs** [comment]
I have squashed the commits and tried to push it normally, but I was asked to do pull  before pushing.I did that and again it was asking to do pull again.To fix this issue I had to force push.Please review it.

**Comment by sharirpcs** [comment]
I have created a new PR to fix this squashing.Please review this URL
https://github.com/lansa/aws-templates/pull/30

**Pull request closed without merging**
