### PR TITLE
Feature/131

### PR DESCRIPTION
**Pull request by sharirpcs**

### CODE REVIEW

**Comment by robe070** [comment]
`CleanupCFNTemplate.ps1` and `DeletePreviousFailedStack.ps1` are the same script. So remove `CleanupCFNTemplate.ps1` and call `DeletePreviousFailedStack.ps1` with the `$DevStack` value

**Comment by robe070** [comment]
I gather from your lack of response that you're working on another project. This would take less than an hour to perform. Just get it done.

**Comment by robe070** [comment]
Thanks for making the change. But you've not provided a url to the Release that tested these changes. In fact the last time you ran something was 4 hours before (5:30pm) this change that you committed at 9:30 pm.

**Comment by sharirpcs** [comment]
Screenshot 2021-06-11 at 10 27 21 AM
FYI I have committed this commit at 4:55 PM IST.Here is the URL to the Release I'm Testing these changes.
https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_release?_a=releases&view=mine&definitionId=6

**Comment by sharirpcs** [comment]
Please close this PR as the issue #131  closed already

**Pull request merged**
