### PR TITLE
CSS-163279: Added support to Windows 2019 and 2 versions of LANSA #80

### PR DESCRIPTION
**Pull request by vamshi-accolite**

### CODE REVIEW

**Review by robe070 — COMMENTED** [review]
I presume you will be adding the code to process these parameters soon?
```
               "ImageSource",
               "AMIId"
```

**Comment by vamshi-accolite** [comment]
> I presume you will be adding the code to process these parameters soon?
> 
> ```
>                "ImageSource",
>                "AMIId"
> ```

Added Condition to ImageSource and passed the parameters based on the conditions.

**Comment by robe070** [comment]
It looks to be correct. Can you provide stacks you've created with 14.2 and 15.0 and custom image to demonstrate its working?

**Comment by robe070** [comment]
I've merged it so that I can test all the images, and then re-opened it. 

Please just demonstrate the custom image working.

**Comment by robe070** [comment]
It seems I can't re-open the PR.

**Comment by robe070** [comment]
In testing the stack I can see that you haven't tested it. :(
master template does not have the new OS listed:
```
        "11WebserverOSVersion": {
            "Default": "win2019",
            "Description": "WebServer Windows operating system version.",
            "Type": "String",
            "AllowedValues": [
                "win2012",
                "win2016",
                "win2019",
            ]
        },
```
I have made this change and pushed it to the `support/scalable` branch. Pull that from `lansa/aws-templates` before you make any other changes.

**Comment by vamshi-accolite** [comment]
Sure Rob.. The testing will be completed as part of #Issue-82(https://github.com/robe070/cookbooks/issues/82)

**Pull request merged**
