### PR TITLE
Feature/131

### PR DESCRIPTION
**Pull request by sharirpcs**

### CODE REVIEW

**Comment by robe070** [comment]
So just to re-iterate what I said in the meeting today, you need to parameterise the scripts and not duplicate them when they differ by some variable. Like there should be only 1 copy of each of these scripts. Not duplicated for each image. Pass in the Image specifics and maybe thats just one parameter. In this case the value would be "w12r2d-14-2"
•	A scripts/w12r2d-14-2_AddNameTag.ps1 (12) 
•	A scripts/w12r2d-14-2_AlternateImageVersion.ps1 (29) 
•	A scripts/w12r2d-14-2_CopyAMIToUS.ps1 (13) 
•	A scripts/w12r2d-14-2_DeletePreviousFailedStack.ps1 (23) 
•	A scripts/w12r2d-14-2_PrintDeploymentOutput.ps1 (4) 
•	A scripts/w12r2d-14-2_SetGateVariable.ps1 (20) 
•	A scripts/w12r2d-14-2_TestCFNDeployment.ps1 (50) 

I see duplicate scripts. Make them 1 with parameters.
CleanupCFNTemplate
TestCFNDeployment
AWSPowershell

ShoeSizes-AWSPowershell-LargeStack.ps1, etc. Make it one.

I haven't necessarily been exhaustive here. I'm expecting you to compare scripts and where they are very similar, replace the differences with parameters. Now you have them out in files, that task should be very easy for you.
I suspect the following are very similar:
scripts/VPCTests-AWSPowershell.ps1
scripts/RunLiveTests-AWSPowershell.ps1

**Comment by robe070** [comment]
I've noticed that Ganesh has attempted to run the new AWS Image Release pipeline. There has been a git error because the commit is not in the LANSA repo. Its in the Celestial Systems repo. I've tried various ways to reference the commit we need, but to no avail. Azure DevOps gets the failure and then retries 4 more times.

To obtain the commit you need to fetch the SHA 4fb4d5abb4d40e3e0e7eb53e91390122a4e4b1b5, creating a branch from it. And then check out that branch. 

```
$ git fetch origin pull/ID/head:BRANCHNAME
$ git checkout BRANCHNAME
```

So in this case it would be :
```
$ git fetch origin pull/17/head:pr17
$ git checkout pr17
```

I know of no way to do this inside a Release pipeline. Only the CI pipeline supports it, it seems. 

I think the best way forward is for you to temporarily change the aws-template fork to your own in the Release pipeline. Then you do not even need to push your changes to the PR. But that will happen anyway now whenever you commit to your branch. Which will be good for me to see.

So this solution meets the 2 prime needs of:
1. You can run it! And without any intervention from me.
2. I can see your commits and review them.

WDYT?

And please can we have some dialog? When I post can you respond in a reasonable timeframe? Like for the post above a reply by COB on your Friday would have been appropriate. Tell me where you are up to.

And if this is not clear, then lets have a meeting soon.

**Comment by robe070** [comment]
Note that I've done a full run of the AWS Image pipeline so you have a full set of artifacts in run 879 (Run 873 only had 1 artifact)

**Comment by robe070** [comment]
I have cancelled all the jobs in the Release that I started on the call. It will take some time to stop. Because its template creation I have also gone into the AWS portal and deleted all 6 stacks. This maybe something you will need to do when testing.

I also suggest that just running the Win2012 14.2 set of jobs will make it easier to tidy up when you need to cancel it all. So, Don't use the default Build Image of 879. Change it to 873 which only contains the Win2012 14.2 artifact:

image

**Comment by robe070** [comment]
Why did nothing get checked in to feature/131 yesterday and why was the Release pipeline not run?

**Comment by rizwancel** [comment]
We tried pushing the changes yesterday but I got access permission error and also could not able to add users in the forked repository. We got it done today and pushed the changes as well.

github_error

**Comment by robe070** [comment]
Also, this commit failed the integration test. On investigation there was no obvious reason for it. So I re-ran the CI pipeline and it succeeded.

**Comment by robe070** [comment]
Note that Issue (2) described above is probably due to using the syntax `$BaseImageName`. It should be `$(BaseImageName)`.
Please use this syntax for ALL references to variables in Strings

**Comment by robe070** [comment]
In order for $(Gate.IsEnabled) to work correctly it must ALWAYS be set. So, at the beginning of `SetVariable.ps1` place this code:
```
Write-Host "##vso[task.setvariable variable=IsEnabled;isOutput=true]False" | Out-Default | Write-Verbose
```
Note this sets the variable to False so that downstream tasks do not throw a fatal error that the variable does not exist.

**Comment by robe070** [comment]
I have reviewed AzureDevOps variable usage. It seems the optimal solution for some of the parameters is to set a Job variable. E.g. $(BaseImageName) should be a Job variable. Additionally, this simplifies the scripts that would have required the `param()` syntax to be added
@rizwancel

**Comment by robe070** [comment]
@sharirpcs @rizwancel 
The reason for the artefact 873 failure in Release 19 is because you've used incorrect syntax for the parameter. It would have worked if you had used:
`-BaseImageName 'w12r2d-14-2'`
That is, it needs to be a literal.
But, I state in the previous comment above, `BaseImageName` needs to be declared as a Job Variable.
ps I notice you've not made changes to any of the other jobs which I think is excellent as you must be sure of your changes before propagating them to all the other jobs.

**Comment by robe070** [comment]
Can you please explain to me why you needed to pass in the $Gate variable properties? e.g. -Gatestack $(Gate.stack)
This should be available to the script anyway.

**Comment by sharirpcs** [comment]
This variable is not able to find inside the script.So we are passing it as an argument.Please refer to the below URL for the error when we are using it inside the script.
https://dev.azure.com/VisualLansa/Lansa%20AWS%20Scalable%20License%20Images/_releaseProgress?_a=release-environment-logs&releaseId=152&environmentId=2182&jobTimelineRecordIdToSelect=2e83dfc6-b834-54a8-1748-8ef63f7d62cb&selectTaskWithIndex=7#
Please suggest if you have any suggestions.

**Comment by robe070** [comment]
> This variable is not able to find inside the script. So we are passing it as an argument

That seems clear and its disappointing. And as that is the case then DeletePreviousFailedStack.ps1 also needs the value of `$(Gate.stack)` passed in. Its coded to expect the stack to not exist, which is usually the case. Testing this requires the stack deployment to fail. Thats not easy to induce. Its bound to happen as development continues and an eye needs to be kept on a stack failing to deploy and then the next run of the pipeline should be checked to ensure the stack gets deleted.

**Comment by robe070** [comment]
Test CFN Deployment : URL Tests task in the Templates - AWS CI pipeline is sometimes timing out. This is a new issue.

The cause is that the TimeoutSec parameter is too small.

I've created an Issue for me to resolve once this PR is complete.

**Comment by robe070** [comment]
@sharirpcs 
The arguments are incorrect on the `Add Name Tag` Tasks
image

**Comment by sharirpcs** [comment]
Screenshot 2021-06-08 at 2 34 16 PM
This has been already updated last week itself and tested successfully.I'm not sure why you are not able to see my updated changes

**Comment by robe070** [comment]
I hit F5 and I could see your changes. Curious because I've not been to that task for a long time and I opened it only today.

**Comment by robe070** [comment]
So I can merge this commit when:
1. You have removed all the unused scripts.
2. There is a successful build using run 879

**Comment by sharirpcs** [comment]
I have added region parameter and removed the CookbooksBranch parameter and it's references.Testing the Pipeline using 873 run for only one artifact

**Comment by robe070** [comment]
I asked you to ensure that a successful CD build had occurred...after making your final changes. I've needed to run the CD Build myself delaying my merging of the PR. Please ensure that before you finish for the day that all of your changes have been tested in a Release (CD) build.

If you make another change whilst a build is still running, like you may have done in this instance, then you have the option to cancel the current build and create a new Release. Depends on what you want to achieve as to whether that suits your needs. For example you may be working on another project for the rest of the day and won't be back to this project today.

**Pull request merged**
