### PR TITLE
163279 added .taskcat.yml for#81

### PR DESCRIPTION
**Pull request by srinivasp898**
163279 added .taskcat.yml for#81 and  created ci pipeline for aws templates

### CODE REVIEW

**Comment by robe070** [comment]
### Task: Deploy CFN Template : BakingDP-TemplateTest
I cannot see  a deleted stack created called `BakingDP-TemplateTest-709`. But that is what the log says it is. What is that name? Its real name should be logged.

### Task: Print Deployment Output
Seems to be doing nothing. What is it meant to be doing?

### Task: Test CFN Deployment : URL Tests
I asked you to log the url that is testing for 200 so when there is an error you know which one failed.

### Task: Aws PowerShell : Test Image Version w12r2d-14-2 Prod
This needs to log what it is testing so that its is clear.

### Task: Copy Database Creation Files to: Artifact Staging Directory
What is this doing? Looks to be copying files that don't exist. I think the task should be deleted.

**Comment by srinivasp898** [comment]
> ### Task: Deploy CFN Template : BakingDP-TemplateTest
> I cannot see a deleted stack created called `BakingDP-TemplateTest-709`. But that is what the log says it is. What is that name? Its real name should be logged.
>
`Hi Robe below in deploy cfn template it is logging stackname.`
image
image


> ### Task: Print Deployment Output
> Seems to be doing nothing. What is it meant to be doing?
  `we followed same steps as azure , but can be removed if not required`
> ### Task: Test CFN Deployment : URL Tests
> I asked you to log the url that is testing for 200 so when there is an error you know which one failed.
`I updated script to print urls when status 2000`
> ### Task: Aws PowerShell : Test Image Version w12r2d-14-2 Prod
> This needs to log what it is testing so that its is clear.
` we are getting image version as  "14.2 EPC142040" after deployment need to update cfn template with sku version , i given default sku version to make build pass`
> ### Task: Copy Database Creation Files to: Artifact Staging Directory
> What is this doing? Looks to be copying files that don't exist. I think the task should be deleted.
 `I added similar to azure pipeline , i am deleting for now.`

**Comment by robe070** [comment]
> > ### Task: Deploy CFN Template : BakingDP-TemplateTest
> > I cannot see a deleted stack created called `BakingDP-TemplateTest-709`. But that is what the log says it is. What is that name? Its real name should be logged.
> 
> `Hi Robe below in deploy cfn template it is logging stackname.`
> image
> 
I didn't find it by scrolling the deleted stacks because there were so many. All I needed to do was put the run number in! Good to learn something.

> > ### Task: Print Deployment Output
> > Seems to be doing nothing. What is it meant to be doing?
> > `we followed same steps as azure , but can be removed if not required`
> > ### Task: Test CFN Deployment : URL Tests
> > I asked you to log the url that is testing for 200 so when there is an error you know which one failed.
> > `I updated script to print urls when status 2000`

The run needs to succeed to check this. The error is due to a mismatch between the master and webserver templates. I'll do a manual build of the support/scalable branch as I know that works...and somebody has broken it. I'll fix it

> > ### Task: Aws PowerShell : Test Image Version w12r2d-14-2 Prod
> > This needs to log what it is testing so that its is clear.
> > ` we are getting image version as  "14.2 EPC142040" after deployment need to update cfn template with sku version , i given default sku version to make build pass`

Thats not what its testing. Its testing the Version, Like '4'.

> > ### Task: Copy Database Creation Files to: Artifact Staging Directory
> > What is this doing? Looks to be copying files that don't exist. I think the task should be deleted.
> > `I added similar to azure pipeline , i am deleting for now.`

You keep using copying from Azure as an excuse. Don't. If its not relevant or not working then you should be raising it with Varun. Every step needs to be reviewed to ensure it is relevant. Thats's part of your task.

**Comment by robe070** [comment]
### Task: Test CFN Deployment : URL Tests
This is now correct.

You just need to resolve
### Task: Aws PowerShell : Test Image Version w12r2d-14-2 Prod
Output the version, e.g. 'Image Version = 4'

**Comment by srinivasp898** [comment]
1.Removed print deployment output task
2.Given skuname as skunameold , need to update  manually once ami id is updated. 
is there anything need to update or we can merge/close this task

**Comment by robe070** [comment]
AMI Ids updated. Please update

**Comment by robe070** [comment]
use latest branch in lansa/aws-templates

**Comment by srinivasp898** [comment]
We are using support/scalable branch in lansa/aws-templates,
Updated correct SKU name  in test image version script in CI pipeline.
image

**Pull request closed without merging**
